export const TOGGLE_PLAYLIST = "TOGGLE_PLAYLIST"
export const APPEND_CHANNEL = "APPEND_CHANNEL"
export const LISTEN_TO = "LISTEN_TO"
export const CREATE_USER = "CREATE_USER"
export const PERSIST_USER = "PERSIST_USER"
export const LOGIN = "LOGIN"
// export const SET_URL = "SET_URL"
